sudo: required
services:
  - docker

before_install:
  - docker build -t fenario/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run fenario/react-test npm test -- --coverage

after_success:
  - docker build -t fenario/multi-client ./client
  - docker build -t fenario/multi-nginx ./nginx
  - docker build -t fenario/multi-server ./server
  - docker build -t fenario/multi-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

- docker push fenario/multi-client
- docker push fenario/multi-nginx
- docker push fenario/multi-server
- docker push fenario/multi-worker